//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace com.rightback.ChocAn.Terminal.com.rightback.webservices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TerminalServiceSoap", Namespace="http://rightback.com/")]
    public partial class TerminalService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback loginProviderOperationCompleted;
        
        private System.Threading.SendOrPostCallback verifyMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback recordClaimOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TerminalService() {
            this.Url = global::com.rightback.ChocAn.Terminal.Properties.Settings.Default.com_rightback_ChocAn_Terminal_com_rightback_webservices_TerminalService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event loginProviderCompletedEventHandler loginProviderCompleted;
        
        /// <remarks/>
        public event verifyMemberCompletedEventHandler verifyMemberCompleted;
        
        /// <remarks/>
        public event getServicesCompletedEventHandler getServicesCompleted;
        
        /// <remarks/>
        public event getServiceCompletedEventHandler getServiceCompleted;
        
        /// <remarks/>
        public event recordClaimCompletedEventHandler recordClaimCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rightback.com/loginProvider", RequestNamespace="http://rightback.com/", ResponseNamespace="http://rightback.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool loginProvider(string providerCode, string terminalCode) {
            object[] results = this.Invoke("loginProvider", new object[] {
                        providerCode,
                        terminalCode});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void loginProviderAsync(string providerCode, string terminalCode) {
            this.loginProviderAsync(providerCode, terminalCode, null);
        }
        
        /// <remarks/>
        public void loginProviderAsync(string providerCode, string terminalCode, object userState) {
            if ((this.loginProviderOperationCompleted == null)) {
                this.loginProviderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginProviderOperationCompleted);
            }
            this.InvokeAsync("loginProvider", new object[] {
                        providerCode,
                        terminalCode}, this.loginProviderOperationCompleted, userState);
        }
        
        private void OnloginProviderOperationCompleted(object arg) {
            if ((this.loginProviderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginProviderCompleted(this, new loginProviderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rightback.com/verifyMember", RequestNamespace="http://rightback.com/", ResponseNamespace="http://rightback.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VerifyMemberResult verifyMember(string memberCode) {
            object[] results = this.Invoke("verifyMember", new object[] {
                        memberCode});
            return ((VerifyMemberResult)(results[0]));
        }
        
        /// <remarks/>
        public void verifyMemberAsync(string memberCode) {
            this.verifyMemberAsync(memberCode, null);
        }
        
        /// <remarks/>
        public void verifyMemberAsync(string memberCode, object userState) {
            if ((this.verifyMemberOperationCompleted == null)) {
                this.verifyMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyMemberOperationCompleted);
            }
            this.InvokeAsync("verifyMember", new object[] {
                        memberCode}, this.verifyMemberOperationCompleted, userState);
        }
        
        private void OnverifyMemberOperationCompleted(object arg) {
            if ((this.verifyMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyMemberCompleted(this, new verifyMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rightback.com/getServices", RequestNamespace="http://rightback.com/", ResponseNamespace="http://rightback.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceViewModel[] getServices() {
            object[] results = this.Invoke("getServices", new object[0]);
            return ((ServiceViewModel[])(results[0]));
        }
        
        /// <remarks/>
        public void getServicesAsync() {
            this.getServicesAsync(null);
        }
        
        /// <remarks/>
        public void getServicesAsync(object userState) {
            if ((this.getServicesOperationCompleted == null)) {
                this.getServicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServicesOperationCompleted);
            }
            this.InvokeAsync("getServices", new object[0], this.getServicesOperationCompleted, userState);
        }
        
        private void OngetServicesOperationCompleted(object arg) {
            if ((this.getServicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServicesCompleted(this, new getServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rightback.com/getService", RequestNamespace="http://rightback.com/", ResponseNamespace="http://rightback.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceViewModel getService(string code) {
            object[] results = this.Invoke("getService", new object[] {
                        code});
            return ((ServiceViewModel)(results[0]));
        }
        
        /// <remarks/>
        public void getServiceAsync(string code) {
            this.getServiceAsync(code, null);
        }
        
        /// <remarks/>
        public void getServiceAsync(string code, object userState) {
            if ((this.getServiceOperationCompleted == null)) {
                this.getServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServiceOperationCompleted);
            }
            this.InvokeAsync("getService", new object[] {
                        code}, this.getServiceOperationCompleted, userState);
        }
        
        private void OngetServiceOperationCompleted(object arg) {
            if ((this.getServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServiceCompleted(this, new getServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rightback.com/recordClaim", RequestNamespace="http://rightback.com/", ResponseNamespace="http://rightback.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RecordClaimResult recordClaim(string providerNumber, string memberNumber, string serviceCode, string comments, System.DateTime dateServiceProvided) {
            object[] results = this.Invoke("recordClaim", new object[] {
                        providerNumber,
                        memberNumber,
                        serviceCode,
                        comments,
                        dateServiceProvided});
            return ((RecordClaimResult)(results[0]));
        }
        
        /// <remarks/>
        public void recordClaimAsync(string providerNumber, string memberNumber, string serviceCode, string comments, System.DateTime dateServiceProvided) {
            this.recordClaimAsync(providerNumber, memberNumber, serviceCode, comments, dateServiceProvided, null);
        }
        
        /// <remarks/>
        public void recordClaimAsync(string providerNumber, string memberNumber, string serviceCode, string comments, System.DateTime dateServiceProvided, object userState) {
            if ((this.recordClaimOperationCompleted == null)) {
                this.recordClaimOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrecordClaimOperationCompleted);
            }
            this.InvokeAsync("recordClaim", new object[] {
                        providerNumber,
                        memberNumber,
                        serviceCode,
                        comments,
                        dateServiceProvided}, this.recordClaimOperationCompleted, userState);
        }
        
        private void OnrecordClaimOperationCompleted(object arg) {
            if ((this.recordClaimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.recordClaimCompleted(this, new recordClaimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rightback.com/")]
    public enum VerifyMemberResult {
        
        /// <remarks/>
        Validated,
        
        /// <remarks/>
        Suspended,
        
        /// <remarks/>
        InvalidMember,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rightback.com/")]
    public partial class ServiceViewModel {
        
        private string codeField;
        
        private string nameField;
        
        private decimal feeField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rightback.com/")]
    public partial class RecordClaimResult {
        
        private bool successField;
        
        private string messageField;
        
        private ServiceViewModel serviceField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public ServiceViewModel service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void loginProviderCompletedEventHandler(object sender, loginProviderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginProviderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginProviderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void verifyMemberCompletedEventHandler(object sender, verifyMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verifyMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verifyMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VerifyMemberResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VerifyMemberResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getServicesCompletedEventHandler(object sender, getServicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceViewModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceViewModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getServiceCompletedEventHandler(object sender, getServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceViewModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceViewModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void recordClaimCompletedEventHandler(object sender, recordClaimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class recordClaimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal recordClaimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RecordClaimResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RecordClaimResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591